### ISSUE TITLE
[Question] MetaSchedule tune_tir output

### ISSUE THREAD

**Issue by bethalianovike** [mlc-ai/notebooks#26]
Hi everyone,

I'm recently trying to run mlc.ai course about optimization using ms.tune_tir ([6.1. Part 1 — Machine Learing Compilation 0.0.1 documentation](https://mlc.ai/chapter_gpu_acceleration/part1.html#leveraging-automatic-program-optimization)).

Here is my source code:

    import tvm
    from tvm.ir.module import IRModule
    from tvm.script import tir as T, relax as R
    from tvm import relax
    from tvm import meta_schedule as ms
    import numpy as np

    target="nvidia/geforce-rtx-3060"
    dev = tvm.cuda(0)

    @tvm.script.ir_module
    class MyModuleMatmul:
        @T.prim_func
        def main(A: T.Buffer((1024, 1024), "float32"), 
                 B: T.Buffer((1024, 1024), "float32"), 
                 C: T.Buffer((1024, 1024), "float32")) -> None: 
            T.func_attr({"global_symbol": "main", "tir.noalias": True})
            for i, j, k in T.grid(1024, 1024, 1024):
                with T.block("C"):
                    vi, vj, vk = T.axis.remap("SSR", [i, j, k])
                    with T.init():
                        C[vi, vj] = 0.0
                    C[vi, vj] = C[vi, vj] + A[vi, vk] * B[vk, vj]

    sch_tuned = ms.tune_tir(
        mod=MyModuleMatmul,
        target=target,
        max_trials_global=64,
        num_trials_per_iter=64,
        work_dir="./tune_tmp_66",
    )

    sch = ms.tir_integration.compile_tir(sch_tuned, MyModuleMatmul, target)
    rt_mod = tvm.build(sch.mod, target=target)

The tune_tir step creates database_tuning_record.json and database_workload.json in the work_dir. 
But when running the compile_tir step, the sch becomes NoneType. So when building the module it produced the following error message:

> AttributeError: 'NoneType' object has no attribute 'mod'

Why did the sch become NoneType, how can I solve the problem? Is the tuning process not run completely?

Thank you for your assistance.

**Comment by gregtozzi** [comment]
Did you try any other combinations of target and dev? When I run your code with `target="llvm --num-cores=1"` and `dev = tvm.cpu`, on my Mac everything works as expected. When I change back to your target and dev (which we know won't work on my machine, of course), I get the same error you're getting. Suggests to me that there's something going on with TVM's attempt to compile to your GPU target. On my machine setting `target` and `dev` to `metal` works fine.

It seems that `compile_tir` calls the `Database.query_schedule` method on `sch`. If no best schedule is found, `query_schedule` returns `None` (referenced code copied below). My theory in your case is that the target you're passing isn't working for some reason.

**`compile_tir`**

```
def compile_tir(
    database: Database,
    mod: Union[ir.IRModule, tir.PrimFunc],
    target: Union[Target, str],
) -> tir.Schedule:
    """Compile a TIR to tir.Schedule, according to the records in the database.

    Parameters
    ----------
    database : Database
        The database of tuning records.
    mod : Union[ir.IRModule, tir.PrimFunc]
        The TIR function to tune.
    target : Union[str, Target]
        The target to tune for.

    Returns
    -------
    sch : tir.Schedule
        The best schedule found in the database.
    """
    mod = _normalize_mod(mod)
    if not isinstance(target, Target):
        target = Target(target)
    return database.query_schedule(mod, target, workload_name="main")
```

**`Database.query_schedule`**
```
def query_schedule(
        self,
        mod: IRModule,
        target: Target,
        workload_name: str,
    ) -> Optional[Schedule]:
        """Query the best schedule of the given workload from the database.

        Parameters
        ----------
        mod : IRModule
            The IRModule to be searched for.
        target : Target
            The target to be searched for.
        workload_name : str
            The name of the workload to be searched for.

        Returns
        -------
        schedule : Optional[tvm.tir.Schedule]
            The best schedule of the given workload; None if not found.
        """
        return _ffi_api.DatabaseQuerySchedule(self, mod, target, workload_name)  # type: ignore # pylint: disable=no-member
```

**Comment by bethalianovike** [comment]
Hi, thank you for your answer.
When I run my code with `target="llvm --num-cores=1"` and `dev = tvm.cpu`, the kernel restarts (kernel appears to have died) after sending the sample to the builder and runner.
Even when I change the size of the tensor from 1024 to 128, the problem still occurs, using `llvm` the kernel will die, and using my GPU target `nvidia/geforce-rtx-3060` the `sch` will be None type.

Can I ask you what the log file (`tvm.meta_schedule.logging.task_0_main`) looks like? Because my log file ends with `Sending n candidates(s) for measurement`. Not sure what the completed log file looks like when you run the `tune_tir` and `compile_tir` completely.

Thank you for your assistance!

**Comment by bethalianovike** [comment]
[Solved]
In my case, downgrading xgboost package version to 1.4.2 will help.
