### ISSUE TITLE
Migrate `code2html` to `IRModule.show()`

### ISSUE THREAD

**Issue by junrushao** [mlc-ai/notebooks#6]
Some notebooks contain verbose `code2html` which I assume could be replaced by `IRModule.show()`:
- https://github.com/mlc-ai/notebooks/blob/main/3_TensorIR_Tensor_Program_Abstraction_Case_Study_Action.ipynb
- https://github.com/mlc-ai/notebooks/blob/main/4_Build_End_to_End_Model.ipynb
- https://github.com/mlc-ai/notebooks/blob/main/5_Automatic_Program_Optimization.ipynb

While some other code is not syntax-highlighted using `IRModule.show()`:
- https://github.com/mlc-ai/notebooks/blob/main/2_tensor_program_abstraction.ipynb

CC: @Hzfengsy @tqchen

**Comment by MasterJH5574** [comment]
Fixed by the latest commit! Thank @junrushao!
